module.exports = {
  "category-empty": "Specify a category. See Reference Data.",
  "category-invalid": "The category is wrong. See Reference Data.",
  "make-empty": "the make is required. See Reference Data.",
  "make-invalid-category": "Make and vehicle-class do not match. See Reference Data.",
  "model-without-make": "the make is required. See Reference Data.",
  "make-model-mismatch": "Make and model do not match. See Reference Data.",
  "model-empty": "For the vehicle-class Car a model is required. See Reference Data.",
  "modeldescription-empty": "The model-description (ad-title) is required.",
  "modeldescription-invalid-chars": "The model description may only contain latin1 characters.",
  "modeldescription-too-long": "The model description may not be longer than 48 characters.",
  "modeldescription-contains-email": "The model description may not contain an e-mail address.",
  "modeldescription-contains-url": "The model description may not contain a URL.",
  "modeldescription-contains-phone": "The model description may not contain a phone number.",
  "damageunrepaired-empty": "Indicate any unrepaired damages (all vehicles except Trailer, SemiTrailer, ConstructionMachine, AgriculturalVehicle, ForkliftTruck).",
  "first-registration required": "A first registration date is required for all used vehicles.",
  "firstregistration-invalid": "The first registration date cannot be in the future.",
  "firstregistration-classiccar-conflict": "the first registration date of a classic vehicle must be at least 20 years in the past.",
  "firstregistration-newcar-conflict": "A new car cannot have a first registration date.",
  "mileage-empty": "Mileage is required. Exception: site-key it GERMANY and vehicle-class is Motorhome.",
  "mileage-new-invalid": "A new car cannot have more than the allowed mileage (500 km).",
  "hu-year-too-low": "Invalid year for HU (TUEV / general-inspection / technical inspection / hu-date). The value must not be before the year 1000.",
  "hu-year-too-high": "Invalid year for HU (TUEV / general-inspection / technical inspection / hu-date). The value must not be more than 6 years in future.",
  "au-year-too-high": "Invalid year for AU (ASU - exhaust-inspection). The value must not be before the year 1000.",
  "au-year-too-low": "Invalid year for AU (ASU - exhaust-inspection). The value must not be more than 6 years in future.",
  "description-empty": "Description is required with site-key FRANCE or ITALY",
  "description-too-long": "The description may not be longer than 3000 characters.",
  "description-contains-email": "The description may not contain an e-mail address.",
  "description-contains-phone": "The description may not contain a phone number.",
  "power-invalid-range": "Power must be in a range from 0 to 999.",
  "fuel-empty": "Fuel is required with site-key FRANCE or ITALY",
  "dealer-price-not-supported": "For FSBO Ads there cannot be a dealer price.",
  "price-empty": "A price must be provided.",
  "dealer-price-to-high": "The dealer's price cannot be higher than the retail price.",
  "delivery-period-xor-delivery-date": "For new Cars either delivery date or delivery period must be provided, but not both at the same time.",
  "condition-classiccar-conflict": "A classic vehicle cannot be a new car.",
  "usagetype-unsupported-for-new-vehicles": "A new vehicle cannot be a vehicle with pre-registration, employees-one-year-car, classic car or demonstration-vehicle.",
  "envkv-values-required": "The marker 'envkv' requires all consumption and emission values and the fuel type being set. EnVKV values are required for new cars and single day registration vehicles.",
  "financing-mandatory-fields-new": "When booking the financing feature, all mandatory financing-values must be present (ratePerCent, monthlyRate, period, grossCreditAmount, closingCosts, rateInsurance, netCreditAmount, bank, nominalInterestRate, typeOfNominalInterestRate).",
  "financing-bad-integrity": "The aggregated value of the financing model may not be less than the consumer price",

};
